---
name: Python Coverage
description: Download (optionally) coverage artifacts, combine them and display results

inputs:
  download:
    description: Whether coverage files should be downloaded
    default: true
  upload-html:
    description: Whether HTML report should be uploaded as an artifact
    default: true
  fail-under:
    description: Fail under N% of coverage
    default: 100

outputs:
  download:
    description: Whether coverage files were downloaded
    value: ${{ inputs.download }}
  upload-html:
    description: Whether HTML report was uploaded as an artifact
    value: ${{ inputs.upload-html }}
  fail-under:
    description: Coverage treshold in % below which action would fail
    default: 100

runs:
  using: composite
  steps:
    - name: Download coverage data.
      uses: actions/download-artifact@9782bd6a9848b53b110e712e20e42d89988822b7 # tag=v3.0.1
    - name: Combine coverage & create HTML report
      shell: bash
      run: |
        poetry run coverage combine --keep $(find . -type f -name ".coverage*")
        poetry run coverage html --skip-empty
        poetry run coverage report --fail-under=100
    - name: Upload HTML report
      if: always()
      uses: actions/upload-artifact@83fd05a356d7e2593de66fc9913b3002723633cb # tag=v3.1.1
      with:
        name: coverage
        path: htmlcov
