---
name: Python Coverage
description: Download (optionally) coverage artifacts, combine them and display results

inputs:
  upload-html:
    description: Whether HTML report should be uploaded as an artifact
    default: true
  fail-under:
    description: Fail under N% of coverage
    default: 100

outputs:
  upload-html:
    description: Whether HTML report was uploaded as an artifact
    value: ${{ inputs.upload-html }}
  fail-under:
    description: Coverage treshold in % below which action will fail
    value: ${{ inputs.fail-under }}

runs:
  using: composite
  steps:
    - name: Download coverage data.
      uses: actions/download-artifact@018cc2cf5baa6db3ef3c5f8a56943fffe632ef53 # v6.0.0
    - name: Combine coverage & create HTML report
      shell: bash
      run: |
        poetry run coverage combine --keep $(find . -type f -name ".coverage*")
        poetry run coverage html --skip-empty
        poetry run coverage report --fail-under=${{ inputs.fail-under }}
    - name: Upload HTML report
      if: ${{ inputs.upload-html }}
      uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5.0.0
      with:
        name: coverage
        path: htmlcov
