---
name: Python Test
description: Run pytest and (optionally) upload coverage as a GitHub artifact

inputs:
  coverage-name:
    description: Name of the uploaded coverage artifact
    required: false
  upload-coverage:
    description: Whether coverage should be uploaded as an artifact.
    default: true
  test-report-name:
    description: Name of the uploaded HTML test report
    required: false
  upload-test-report:
    description: Whether HTML test report should be uploaded as an artifact.
    default: true

outputs:
  coverage-name:
    description: Name of the uploaded coverage artifact
    value: ${{ inputs.artifact-name }}
  upload-coverage:
    description: Whether coverage was uploaded as an artifact.
    value: ${{ inputs.upload-coverage }}
  test-report-name:
    description: Name of the uploaded HTML test report
    value: ${{ inputs.test-report-name }}
  upload-test-report:
    description: Whether HTML test report should be uploaded as an artifact.
    value: ${{ inputs.upload-test-report }}

runs:
  using: composite
  steps:
    - name: Run PR test suite
      shell: bash
      run: >
        poetry run pytest -n auto --pretty --cov=src
        --html=.report.html --self-contained-html test
    - name: Upload coverage data
      if: inputs.upload-coverage
      uses: actions/upload-artifact@50769540e7f4bd5e21e526ee35c689e35e0d6874 # v4.4.0
      with:
        name: ${{ inputs.coverage-name }}
        path: .coverage*
    - name: Upload test report
      if: inputs.upload-test-report
      uses: actions/upload-artifact@50769540e7f4bd5e21e526ee35c689e35e0d6874 # v4.4.0
      with:
        name: ${{ inputs.test-report-name }}
        path: .report.html
