---
name: Python Docstrings Coverage

on:
  pull_request:
    branches:
      - main
    paths:
      - "**.py"

jobs:
  coverage:
    if: ${{ ! contains(github.repository, 'template') }}
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@2e205a28d0e1da00c5f53b161f4067b052c61f34 # tag=v1.5.0
        with:
          egress-policy: block
          allowed-endpoints: >
            api.github.com:443
            files.pythonhosted.org:443
            github.com:443
            pypi.org:443
      - name: Checkout repository
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # tag=v3.1.0
      - name: Setup Dependencies
        uses: ./.github/actions/setup-poetry
      - name: Run docstrings coverage
        run: poetry run interrogate -c pyproject.toml .
