---
name: Security Pysa

on:
  pull_request:
    branches:
      - main
    paths:
      - '**.py'
      - '**.yml'
      - '**.yaml'
  schedule:
    - cron: 0 3 * * *

jobs:
  pysa:
    if: ${{ ! github.event.repository.private }}
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@2e205a28d0e1da00c5f53b161f4067b052c61f34 # tag=v1.5.0
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs
      - name: Checkout repository
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # tag=v3.1.0
      - name: Setup Dependencies
        uses: ./.github/actions/setup-poetry
      - name: Export requirements.txt
        run: poetry export -f requirements.txt --output requirements.txt
      - name: Run Pysa Action
        uses: facebook/pysa-action@f46a63777e59268613bd6e2ff4e29f144ca9e88b # tag=v0.0.1
        with:
          repo-directory: ./
          requirements-path: requirements.txt
          infer-types: true
          include-default-sapp-filters: true
